networks:
    insecption:
        name: "insecption"
        driver: bridge

volumes:
    DB:
        name: "mariadb"
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/lucabohm/data/db # /home/lbohm/data
    WP:
        name: 'wordpress'
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/lucabohm/data/wp # /home/lbohm/data

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        volumes:
            - "WP:/var/www/html"
        depends_on:
            wordpress:
                condition: service_healthy
        networks:
            - insecption
        expose:
            - "9000"
        restart: on-failure

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordPress
            dockerfile: Dockerfile
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - "WP:/var/www/html"
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_NAME: wp_db
            WORDPRESS_DB_USER: wp_user
            WORDPRESS_DB_PASSWORD: wp_pass
            WORDPRESS_TEST_USER: test
            WORDPRESS_TEST_PASSWORD: starwars
            WORDPRESS_TEST_USER_EMAIL: test@test.com
        healthcheck:
            test: ["CMD-SHELL", "pgrep php-fpm8.2"]
            interval: 30s
            timeout: 5s
            retries: 3
        networks:
            - insecption
        expose:
            - "9000"
            - "3306"
        restart: on-failure

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariaDb
            dockerfile: Dockerfile
        volumes:
            - "DB:/var/lib/mysql:rw"
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: wp_db
            MYSQL_USER: wp_user
            MYSQL_PASSWORD: wp_pass
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 15s
        networks:
            - insecption
        expose:
            - "3306"
        restart: on-failure
