networks:
    inception:
        name: "inception"
        driver: bridge

volumes:
    DB:
      name: "mariadb"
      driver: local
      driver_opts:
          type: none
          o: bind
          device: /home/lbohm/data
    WP:
      name: 'wordpress'
      driver: local
      driver_opts:
          type: none
          o: bind
          device: /home/lbohm/data

services:
    nginx:
      container_name: nginx
      build:
          context: ./requirements/nginx
          dockerfile: Dockerfile
      ports:
          - "443:443"
      volumes:
          - "WP:/var/www/html"
      depends_on:
          wordpress:
              condition: service_healthy
      networks:
          - inception
      expose:
          - "9000"
      restart: on-failure

    wordpress:
      container_name: wordpress
      build:
          context: ./requirements/wordPress
          dockerfile: Dockerfile
      depends_on:
          mariadb:
              condition: service_healthy
          redis:
              condition: service_healthy
      volumes:
          - "WP:/var/www/html"
      environment:
          - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
          - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
          - WORDPRESS_DB_USER=${MYSQL_USER}
          - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
          - WORDPRESS_USER=${WORDPRESS_USER}
          - WORDPRESS_USER_PASSWORD=${WORDPRESS_PASSWORD}
          - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL}
          - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
          - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
          - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      healthcheck:
          test: ["CMD-SHELL", "pgrep php-fpm7.4"]
          interval: 10s
          timeout: 5s
          retries: 3
      networks:
          - inception
      expose:
          - "9000"
          - "3306"
      restart: on-failure

    mariadb:
      container_name: mariadb
      build:
          context: ./requirements/mariaDb
          dockerfile: Dockerfile
      volumes:
          - "DB:/var/lib/mysql"
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 3
      networks:
          - inception
      expose:
          - "3306"
      restart: on-failure

    redis:
      container_name: redis
      build:
        context: ./requirements/bonus/redis
        dockerfile: Dockerfile
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 3
      networks:
        - inception
      expose:
        - "6379"
      restart: on-failure

    ftp:
      container_name: ftp
      build:
        context: ./requirements/bonus/ftp
        dockerfile: Dockerfile
      volumes:
          - "WP:/var/www/html"
      depends_on:
          wordpress:
            condition: service_healthy
      ports:
        - "21:21"
        - "10000-10100:10000-10100"
      restart: on-failure

    adminer:
      container_name: adminer
      build:
        context: ./requirements/bonus/adminer
        dockerfile: Dockerfile
      volumes:
        - "WP:/var/www/html"
      depends_on:
        mariadb:
          condition: service_healthy
      ports:
        - "8080:8080"
      networks:
        - inception
      restart: on-failure

    cadvisor:
      container_name: cadvisor
      build:
        context: ./requirements/bonus/cadvisor
        dockerfile: Dockerfile
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:ro"
        - "/sys:/sys:ro"
        - "/var/lib/docker/:/var/lib/docker:ro"
        - "/dev/disk/:/dev/disk:ro"
      ports:
        - "4000:8080"
      networks:
        - inception
      restart: on-failure

    webside:
      container_name: webside
      build:
        context: ./requirements/bonus/webside
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      restart: on-failure
